name: Check Style

on: [push, pull_request]

jobs:

  style:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master

    - name: Only fetch Style PHP submodule
      run: git submodule update --init -- .style

    - name: Install latest PHP-CS-Fixer
      run: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.17.2/php-cs-fixer.phar

    - name: Run Checks
      run: php php-cs-fixer-v2.phar fix --config=.style/.php_cs -v --dry-run --allow-risky=yes .
